# Generated by Django 3.1.7 on 2021-03-31 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blood_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=20)),
                ('dep_info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_1.student_model')),
            ],
        ),
    ]
