# Generated by Django 3.1.7 on 2021-03-31 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_1', '0002_blood_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blood_group',
            new_name='blood_model',
        ),
    ]
