# Generated by Django 3.1.7 on 2021-03-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_1', '0003_auto_20210331_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=20)),
                ('subject_info', models.ManyToManyField(to='test_1.student_model')),
            ],
        ),
    ]
