# Generated by Django 3.1.7 on 2021-04-01 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_1', '0005_company_employee_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='emp_info',
        ),
        migrations.AddField(
            model_name='employee_model',
            name='company_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_1.company'),
        ),
    ]
