# Generated by Django 3.1.7 on 2021-04-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_1', '0006_auto_20210401_0526'),
    ]

    operations = [
        migrations.CreateModel(
            name='assing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assing_name', models.CharField(max_length=30)),
                ('assing_info', models.ManyToManyField(to='test_1.student_model')),
            ],
        ),
    ]
