# Generated by Django 3.1.7 on 2021-03-24 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0005_auto_20210322_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='_info',
        ),
        migrations.AddField(
            model_name='department',
            name='_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='one.employee'),
        ),
    ]
