# Generated by Django 3.1.7 on 2021-03-24 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0007_auto_20210324_0632'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='d_epartment',
            new_name='department1',
        ),
        migrations.RenameModel(
            old_name='e_mployee',
            new_name='employee1',
        ),
    ]
