# Generated by Django 3.1.7 on 2021-03-24 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_model',
            old_name='name',
            new_name='name_1',
        ),
    ]
