# Generated by Django 3.1.7 on 2021-03-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_projects_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='_info',
        ),
        migrations.AddField(
            model_name='projects',
            name='_info',
            field=models.ManyToManyField(to='new.student'),
        ),
    ]
